[theme]
# Muda a base para um tema claro e leve
base = "light"

# Verde Querino (Para botões e destaques)
primaryColor = "#aecb36"

# Branco/Gelo Querino (Fundo principal limpo)
backgroundColor = "#fdfdfd"

# Azul Escuro Querino (Para o menu lateral, criando um belo contraste)
secondaryBackgroundColor = "#1a1e38"

# Azul Escuro Querino (Para os textos, garantindo leitura perfeita)
textColor = "#1a1e38"