JWT_SECRET = "sua_chave_secreta_aqui_2026"

# Define qual ambiente o código vai ler localmente ("db_homolog" ou "db_prod")
ACTIVE_ENV = "db_prod"

[db_homolog]
DB_USER = "postgres.leombjktflhropvdblnv"
DB_PASS = "Acess@dados26"
DB_HOST = "aws-0-sa-east-1.pooler.supabase.com"
DB_PORT = "5432"
DB_NAME = "postgres"

[db_prod]
DB_USER = "postgres.dychhsqpvqtwaslujbir"
DB_PASS = "Acess@bi2026"
DB_HOST = "aws-0-sa-east-1.pooler.supabase.com"
DB_PORT = "5432"
DB_NAME = "postgres"